apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: derpserver
    labels:
        release: dev
spec:
    selector:
        matchLabels:
            release: dev
    template:
        metadata:
            labels:
                release: dev
        spec:
            containers:
              - name: derpserver
                image: "gcr.io/virtual-dogfish-241620/webserver:dev"
                env:
                - name: DATABASE_URI
                  value: "postgresql://dev:s3cr3t@10.5.128.3:5432/dev"
                - name: REDIS_HOST
                  value: "10.0.0.11"
---
apiVersion: v1
kind: Service
metadata:
    name: derpserver
    annotations:
        cloud.google.com/load-balancer-type: "External"
    labels:
        release: dev
spec:
    selector:
        release: dev
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: derpserver
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: derpserver
  targetCPUUtilizationPercentage: 80

