steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/virtual-dogfish-241620/github.com/eanupinterview/webserver::$COMMIT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/virtual-dogfish-241620/github.com/eanupinterview/webserver:latest', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/virtual-dogfish-241620/github.com/eanupinterview/webserver:$BRANCH_NAME', '.' ]
images:
- 'gcr.io/virtual-dogfish-241620/github.com/eanupinterview/webserver:latest'
- 'gcr.io/virtual-dogfish-241620/github.com/eanupinterview/webserver:$COMMIT_SHA'
- 'gcr.io/virtual-dogfish-241620/github.com/eanupinterview/webserver:$BRANCH_NAME'
tags:
- "cloudbuild"

