steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/virtual-dogfish-241620/webserver:$COMMIT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/virtual-dogfish-241620/webserver:latest', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/virtual-dogfish-241620/webserver:$BRANCH_NAME', '.' ]
images:
- 'gcr.io/virtual-dogfish-241620/webserver:latest'
- 'gcr.io/virtual-dogfish-241620/webserver:$COMMIT_SHA'
- 'gcr.io/virtual-dogfish-241620/webserver:$BRANCH_NAME'

