apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: derpserver
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: derpserver
  targetCPUUtilizationPercentage: 80

