apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: derpjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            cloud.google.com/gke-nodepool: default-pool
          containers:
          - name: derpjob
            args:
            - /usr/local/earnup/derp_job.py
            command:
            - /usr/local/bin/python
            image: gcr.io/virtual-dogfish-241620/webserver:latest
            env:
            - name: DATABASE_URI
              value: "postgresql://sandbox:s3cr3t@10.5.128.3:5432/sandbox"
            - name: REDIS_HOST
              value: "10.0.0.3"
            - name: REDIS_PORT
              value: "6379"
            - name: PORT
              value: "8080"


