apiVersion: v1
kind: Service
metadata:
  name: derpserver
  annotations:
    cloud.google.com/load-balancer-type: "External"
  labels:
    app: derpserver
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: derpserver

